application: cmbalance
version: 1
runtime: python
api_version: 1

handlers:
- url: /stats
  script: pages/stats.py

- url: /admin|/admin/.*\.html
  script: pages/admin.py
  
- url: /rpc
  script: pages/rpc.py
  
- url: /
  script: pages/browse.py
  
- url: /static
  static_dir: static